### ISSUE TITLE
News API

### ISSUE THREAD

**Issue by MinJY** [Nexters/VolleyTalk_Server#15]
1. 테스트 데이터를 확인해보았는데, 이미지는 항상 5개로 고정인가요?
상단에 PhotoNews랑 ThumbnailNews에 각각 몇 개의 이미지를 적용하면 될까요?

2. 뉴스가 게재된 곳의 정보가 필요해요. ex) 뉴스데일리, STN sports, ....

3. API가 검색결과 편집한 거라 그런지 모든 타이틀 및 내용에 포함된 곳에 <b>배구</b> 요렇게 뜨는데,
<b>태그 제거해주실 수 있나요? 만약 번거로우시면 이 부분은 그냥 클라이언트에서 제거할게요.

4. 오늘의 경기는 별도로 이후에 진행하면 되죠?

**Comment by kys9261** [comment]
1. 지금 이미지는 5개로 고정시켜뒀는데 상단에 3개. / 썸네일에 3개 6개로 해두면 될것 같음.
2. 따로 게제된곳의 정보를 제공하지는 않아서 도메인으로 따오거나 해야할것 같은데. 어디에 사용하려고??
3. 태그는 확인해보고 제거하겠음.
4. 오늘의 경기는 제일 나중에 API 개발하려함(아직 DB 구축이 안되어있음)

**Comment by kys9261** [comment]
1. 이미지 6개까지로 수정완료.
3. 제거 완료.
