### ISSUE TITLE
/player/list/{gender} API

### ISSUE THREAD

**Issue by MinJY** [Nexters/VolleyTalk_Server#18]
/player/list/{gender} API에서
현재 아래와 같은 방식으로 되어있는데요,

 "1": [
    {
      "seq": 1,
      "teamseq": 1,
      "backnumber": 6,
      "name": "가스파리니",
      "physical": "202cm, 95kg",
      "likecount": 0,
      "postcount": 0,
      "like": [],
      "follow": []
    },
    {
      "seq": 2,

 int값이 json name으로 되어있어서 파싱할 때 약간 어려움을 겪고 있는데
혹시 아래와 같은 방식으로 바꿔주실 수 있으신가요?

"team" : 1,
"player" : [ 
 {
      "seq": 1,
      "teamseq": 1,
      "backnumber": 6,
      "name": "가스파리니",
      "physical": "202cm, 95kg",
      "likecount": 0,
      "postcount": 0,
      "like": [],
      "follow": []
    },
    {
      "seq": 2,

**Comment by kys9261** [comment]
이슈 해결.
